### ISSUE TITLE
Tracking Bugs...

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#67]
**Running list to track any bugs we need to pin down:**

- [x] Authentication problems: What if a user tries to use someone else's FCC account? What if multiple people try to do this?
- [x] Navbar inconsistency when logged in/out.
- [x] Trying to private chat a user that doesn't exist — what happens?
- [x] When does private chat history get loaded? — Possibly introducing loading states throughout the app for various data if the data has not arrived from the server yet (this is probably a good idea).
- [x] Private chat: verify socket.io updates are being handled correctly.
- [x] If a new user messages in chat, this user will not be part of the community on connected users apps and the app will break if you try to start a private chat with them.
- [x] Online status does not update in real time
- [x] Routing problems... such as:
- [x] Navigation to another private chat from within a private chat does not work correctly: may have fixed this, need to verify — tried to fix *again*...
- [x] Notification icons in private chat window are positioned relative to each user.

**Comment by bonham000** [comment]
**Looking good!** :robot: 🚀
